services:
  app:
    build: .
    container_name: app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src/
      - ./tests:/app/tests/
    command: "fastapi run ./src/main.py --reload"
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.0
    ports:
      - "6379:6379"

volumes:
  data:

